# Generated by Django 3.2.7 on 2021-09-23 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, height_field=100, upload_to='images', width_field=100),
        ),
    ]
